### ISSUE TITLE
Translation of desktop and appdata files

### ISSUE THREAD

**Issue by Nick-Hall** [gramps-project/flatpak#5]
We should be using metadata files that include translations.  The translations are merged into the files as part of the build process.

@OzarkShepherd Do your new versions of these files differ much from the old ones?  Perhaps we should change the originals.

**Comment by OzarkShepherd** [comment]
The new metadata files were started from scratch according to flathub guidelines https://github.com/flathub/flathub/wiki/AppData-Guidelines and started with the AppStream generator https://www.freedesktop.org/software/appstream/metainfocreator/#/  I kept in mind that it would be used to generate the webpage for Gramps at flathub and was primarily keeping flathub in mind.  That is why there is a long description and screenshots in the new metadata files.  I thought it would be easier to make new metadata files and move them into the specified location for flathub, then to request that the 5.1.3 source be altered to accommodate flathub.  To be honest, I don't know python well enough to quickly determine how the old metadata files would look like in other languages.

**Comment by Nick-Hall** [comment]
PR [#1143](https://github.com/gramps-project/gramps/pull/1143) from @a-andre in the main _gramps_ repository is aimed making our appdata, desktop and icon files compatible with Flatpak conventions.  I would also consider backporting these changes to _gramps51_.

**Comment by a-andre** [comment]
Regarding OARS, @OzarkShepherd where does Gramps share location or contact details with other users?

There shouldn't be a flatpak specific description. See https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#id-1.5.3.4.3.6 for what could be its content. The current one is in contrast to "Do not be too geeky. Aim for an intelligent semi-technical reader."

As much as possible optional dependencies should be included in the flatpak package to reduce the need for changing the upstream description.

**Comment by OzarkShepherd** [comment]
@a-andre When users share gedcom files, there are two places where location and contact details could be shared with other users.  First in the person's profile if they are in the file, and second in the researcher tab of the Preferences.  Of course it is completely voluntary to share genealogical information with other users, but OARS did not ask if the information was voluntary in the questionnaire.

As for not having a flatpak specific description, there is a lot of information that flathub wants for its page for the app, like OARS and screenshots, which are not very useful otherwise.  I don't see much point in including the flathub description and screenshots in with the other builds outside flatpak.

**Comment by OzarkShepherd** [comment]
Since BSDDB3 now works in the pull request, the workaround for BSDDB3 in the description isn't necessary anymore and I took it out.

**Comment by a-andre** [comment]
> When users share gedcom files, there are two places where location and contact details could be shared with other users. First in the person's profile if they are in the file, and second in the researcher tab of the Preferences. Of course it is completely voluntary to share genealogical information with other users, but OARS did not ask if the information was voluntary in the questionnaire.

So it's about metadata of files generated by Gramps.
If @Nick-Hall (or others responsible) agrees with this position, [OARS in Gramps repo](https://github.com/gramps-project/gramps/blob/master/data/gramps.appdata.xml.in#L46) should be updated.

There is an upstream discussion about it https://github.com/hughsie/oars/issues/19

> As for not having a flatpak specific description, there is a lot of information that flathub wants for its page for the app, like OARS and screenshots, which are not very useful otherwise. I don't see much point in including the flathub description and screenshots in with the other builds outside flatpak.

Information in appdata files are not only used by flathub, but also by tools like [KDE Discover](https://userbase.kde.org/Discover) and [Gnome Software](https://wiki.gnome.org/Apps/Software/).
So the same description should be used for flatpak version and other builds because it's the same Gramps just shipped another way.

**Comment by Nick-Hall** [comment]
I agree.  We should present a consistent public image in all software managers.  I notice that the Gnome software application can also display packages available in flathub.

We should use the appdata and desktop file from core Gramps which will also be translated.

I read the OARS link, but I'm still not entirely sure what is the correct approach.  My concern is that if we include entries then it may be interpreted that Gramps is not suitable for users under 18 years of age.

The other thing that may need changing are the links to the screenshots.  I'm not sure that the links would stay the same if we updated the images.  I'll see if I can get our web admin to create some static links for us.

**Comment by OzarkShepherd** [comment]
I put the translations back in the desktop and appdata files, and used the desktop and appdata files provided by Nick from the main branch into my pull request.
